# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'loginPage.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QStackedWidget, QWidget)
import img_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1024, 768)
        self.stackedWidget = QStackedWidget(Form)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 1021, 771))
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.widget = QWidget(self.page_3)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(30, 30, 961, 731))
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 80, 541, 561))
        self.label.setStyleSheet(u"background-image: url(:/pics/images/Summary.png);\n"
"border-top-left-radius: 50px;")
        self.label.setScaledContents(True)
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(540, 80, 411, 561))
        self.label_2.setStyleSheet(u"background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius: 50px;")
        self.Signin_Label = QLabel(self.widget)
        self.Signin_Label.setObjectName(u"Signin_Label")
        self.Signin_Label.setGeometry(QRect(670, 130, 131, 51))
        font = QFont()
        font.setPointSize(40)
        font.setBold(True)
        self.Signin_Label.setFont(font)
        self.Signin_Label.setStyleSheet(u"color:rgba(0,0,0,150);\n"
"")
        self.lineEditUserLogin = QLineEdit(self.widget)
        self.lineEditUserLogin.setObjectName(u"lineEditUserLogin")
        self.lineEditUserLogin.setGeometry(QRect(600, 250, 311, 51))
        font1 = QFont()
        font1.setPointSize(18)
        self.lineEditUserLogin.setFont(font1)
        self.lineEditUserLogin.setStyleSheet(u"background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,100);\n"
"padding-bottom:7px;")
        self.loginButton = QPushButton(self.widget)
        self.loginButton.setObjectName(u"loginButton")
        self.loginButton.setGeometry(QRect(600, 440, 311, 71))
        font2 = QFont()
        font2.setPointSize(20)
        font2.setBold(True)
        self.loginButton.setFont(font2)
        self.loginButton.setStyleSheet(u"QPushButton#loginButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11,131,120,160), stop:1 rgba(85,98,112,160));\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#loginButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11,131,120,200), stop:1 rgba(85,98,112,200));\n"
"}\n"
"\n"
"QPushButton#loginButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11,131,120,120), stop:1 rgba(85,98,112,120));\n"
"}\n"
"")
        self.GoRegisterButton = QPushButton(self.widget)
        self.GoRegisterButton.setObjectName(u"GoRegisterButton")
        self.GoRegisterButton.setGeometry(QRect(600, 530, 311, 71))
        self.GoRegisterButton.setFont(font2)
        self.GoRegisterButton.setStyleSheet(u"QPushButton#GoRegisterButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11,131,120,120), stop:1 rgba(85,98,112,120));\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#GoRegisterButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11,131,120,160), stop:1 rgba(85,98,112,160));\n"
"}\n"
"\n"
"QPushButton#GoRegisterButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11,131,120,80), stop:1 rgba(85,98,112,80));\n"
"}\n"
"")
        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 120, 521, 81))
        self.label_4.setStyleSheet(u"background-color: rgba(0,0,0,75);")
        self.label_5 = QLabel(self.widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 130, 501, 61))
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(u"color: white;\n"
"")
        self.lineEditPassLogin = QLineEdit(self.widget)
        self.lineEditPassLogin.setObjectName(u"lineEditPassLogin")
        self.lineEditPassLogin.setGeometry(QRect(600, 350, 311, 51))
        self.lineEditPassLogin.setFont(font1)
        self.lineEditPassLogin.setStyleSheet(u"background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,100);\n"
"padding-bottom:7px;")
        self.lineEditPassLogin.setEchoMode(QLineEdit.Password)
        self.closeButton = QPushButton(self.widget)
        self.closeButton.setObjectName(u"closeButton")
        self.closeButton.setGeometry(QRect(910, 90, 31, 32))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setBaseSize(QSize(0, 0))
        self.closeButton.setStyleSheet(u"QPushButton#closeButton {\n"
"    border: none;\n"
"    border-radius: 10px; /* set the initial border radius */\n"
"}\n"
"\n"
"QPushButton#closeButton:hover {\n"
"    border: 2px dashed grey; /* set the border to a solid color when hovering */\n"
"    border-radius: 50%; /* set the border radius to create a circle */\n"
"}\n"
"")
        icon = QIcon()
        icon.addFile(u":/pics/images/x-button.png", QSize(), QIcon.Normal, QIcon.Off)
        self.closeButton.setIcon(icon)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.widget_2 = QWidget(self.page_4)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(30, 30, 961, 731))
        self.label_6 = QLabel(self.widget_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 80, 541, 561))
        self.label_6.setStyleSheet(u"background-image: url(:/pics/images/Summary.png);\n"
"border-top-left-radius: 50px;")
        self.label_6.setScaledContents(True)
        self.label_7 = QLabel(self.widget_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(540, 80, 411, 561))
        self.label_7.setStyleSheet(u"background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius: 50px;")
        self.Reigstration_Label = QLabel(self.widget_2)
        self.Reigstration_Label.setObjectName(u"Reigstration_Label")
        self.Reigstration_Label.setGeometry(QRect(630, 130, 241, 51))
        self.Reigstration_Label.setFont(font)
        self.Reigstration_Label.setStyleSheet(u"color:rgba(0,0,0,150);\n"
"")
        self.lineEditUserRegister = QLineEdit(self.widget_2)
        self.lineEditUserRegister.setObjectName(u"lineEditUserRegister")
        self.lineEditUserRegister.setGeometry(QRect(600, 210, 311, 51))
        self.lineEditUserRegister.setFont(font1)
        self.lineEditUserRegister.setStyleSheet(u"background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,100);\n"
"padding-bottom:7px;")
        self.RegisterButton = QPushButton(self.widget_2)
        self.RegisterButton.setObjectName(u"RegisterButton")
        self.RegisterButton.setGeometry(QRect(600, 450, 311, 71))
        self.RegisterButton.setFont(font2)
        self.RegisterButton.setStyleSheet(u"QPushButton#RegisterButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11,131,120,160), stop:1 rgba(85,98,112,160));\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#RegisterButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11,131,120,200), stop:1 rgba(85,98,112,200));\n"
"}\n"
"\n"
"QPushButton#RegisterButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11,131,120,120), stop:1 rgba(85,98,112,120));\n"
"}\n"
"")
        self.label_9 = QLabel(self.widget_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 120, 521, 81))
        self.label_9.setStyleSheet(u"background-color: rgba(0,0,0,75);")
        self.label_10 = QLabel(self.widget_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 130, 501, 61))
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(u"color: white;\n"
"")
        self.lineEditUserPassword = QLineEdit(self.widget_2)
        self.lineEditUserPassword.setObjectName(u"lineEditUserPassword")
        self.lineEditUserPassword.setGeometry(QRect(600, 300, 311, 51))
        self.lineEditUserPassword.setFont(font1)
        self.lineEditUserPassword.setStyleSheet(u"background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,100);\n"
"padding-bottom:7px;")
        self.lineEditUserPassword.setEchoMode(QLineEdit.Password)
        self.closeButton_2 = QPushButton(self.widget_2)
        self.closeButton_2.setObjectName(u"closeButton_2")
        self.closeButton_2.setGeometry(QRect(910, 90, 31, 32))
        sizePolicy.setHeightForWidth(self.closeButton_2.sizePolicy().hasHeightForWidth())
        self.closeButton_2.setSizePolicy(sizePolicy)
        self.closeButton_2.setBaseSize(QSize(0, 0))
        self.closeButton_2.setStyleSheet(u"QPushButton#closeButton_2 {\n"
"    border: none;\n"
"    border-radius: 10px; /* set the initial border radius */\n"
"}\n"
"\n"
"QPushButton#closeButton_2:hover {\n"
"    border: 2px dashed grey; /* set the border to a solid color when hovering */\n"
"    border-radius: 50%; /* set the border radius to create a circle */\n"
"}\n"
"")
        self.closeButton_2.setIcon(icon)
        self.lineEditUserPassword_2 = QLineEdit(self.widget_2)
        self.lineEditUserPassword_2.setObjectName(u"lineEditUserPassword_2")
        self.lineEditUserPassword_2.setGeometry(QRect(600, 370, 311, 51))
        self.lineEditUserPassword_2.setFont(font1)
        self.lineEditUserPassword_2.setStyleSheet(u"background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,100);\n"
"padding-bottom:7px;")
        self.lineEditUserPassword_2.setEchoMode(QLineEdit.Password)
        self.goSigninButton = QPushButton(self.widget_2)
        self.goSigninButton.setObjectName(u"goSigninButton")
        self.goSigninButton.setGeometry(QRect(600, 540, 311, 71))
        self.goSigninButton.setFont(font2)
        self.goSigninButton.setStyleSheet(u"QPushButton#goSigninButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11,131,120,120), stop:1 rgba(85,98,112,120));\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#goSigninButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11,131,120,160), stop:1 rgba(85,98,112,160));\n"
"}\n"
"\n"
"QPushButton#goSigninButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11,131,120,80), stop:1 rgba(85,98,112,80));\n"
"}\n"
"")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.label_3 = QLabel(self.page_5)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(-30, -30, 1071, 101))
        self.label_3.setStyleSheet(u"background-color: rgb(81,74,248);")
        self.label_8 = QLabel(self.page_5)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(70, 30, 121, 21))
        self.label_8.setFont(font2)
        self.label_8.setStyleSheet(u"color: white;\n"
"")
        self.tabsButton = QPushButton(self.page_5)
        self.tabsButton.setObjectName(u"tabsButton")
        self.tabsButton.setGeometry(QRect(20, 20, 41, 41))
        self.tabsButton.setStyleSheet(u"QPushButton#tabsButton {\n"
"    border: none;\n"
"    background-color: rgb(81,74,248);\n"
"   qproperty-iconSize: 40px;\n"
"    border-radius: 10px; /* set the initial border radius */\n"
"}\n"
"\n"
"QPushButton#tabsButton:hover {\n"
"    background-color: rgb(81,74,170);\n"
"}\n"
"")
        icon1 = QIcon()
        icon1.addFile(u":/pics/images/menu.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabsButton.setIcon(icon1)
        self.label_11 = QLabel(self.page_5)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(0, 70, 1021, 701))
        self.label_11.setStyleSheet(u"background-color: rgb(250,250,250);")
        self.label_12 = QLabel(self.page_5)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(0, 80, 241, 691))
        self.label_12.setStyleSheet(u"background-color: rgb(255,255,255);")
        self.label_13 = QLabel(self.page_5)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(260, 146, 221, 61))
        self.label_13.setStyleSheet(u"background-color: rgb(255,255,255);")
        self.label_14 = QLabel(self.page_5)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(510, 146, 221, 61))
        self.label_14.setStyleSheet(u"background-color: rgb(255,255,255);")
        self.label_15 = QLabel(self.page_5)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(760, 146, 221, 61))
        self.label_15.setStyleSheet(u"background-color: rgb(255,255,255);")
        self.label_16 = QLabel(self.page_5)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(260, 190, 221, 21))
        self.label_16.setStyleSheet(u"background-color: rgb(178,241,149);\n"
"")
        self.label_17 = QLabel(self.page_5)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(510, 190, 221, 21))
        self.label_17.setStyleSheet(u"background-color: rgb(164,202,247);\n"
"")
        self.label_18 = QLabel(self.page_5)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(760, 190, 221, 21))
        self.label_18.setStyleSheet(u"background-color: rgb(213,131,131);\n"
"")
        self.label_19 = QLabel(self.page_5)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(270, 150, 111, 16))
        font3 = QFont()
        font3.setBold(True)
        self.label_19.setFont(font3)
        self.label_19.setStyleSheet(u"color: rgb(148,148,148);")
        self.label_20 = QLabel(self.page_5)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(520, 150, 121, 16))
        self.label_20.setFont(font3)
        self.label_20.setStyleSheet(u"color: rgb(148,148,148);")
        self.label_21 = QLabel(self.page_5)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(770, 150, 111, 16))
        self.label_21.setFont(font3)
        self.label_21.setStyleSheet(u"color: rgb(148,148,148);")
        self.label_22 = QLabel(self.page_5)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(270, 170, 16, 31))
        font4 = QFont()
        font4.setPointSize(20)
        self.label_22.setFont(font4)
        self.label_22.setStyleSheet(u"color: rgb(0,0,0);")
        self.label_23 = QLabel(self.page_5)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(520, 170, 16, 31))
        self.label_23.setFont(font4)
        self.label_23.setStyleSheet(u"color: rgb(0,0,0);")
        self.label_24 = QLabel(self.page_5)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(770, 170, 16, 31))
        self.label_24.setFont(font4)
        self.label_24.setStyleSheet(u"color: rgb(0,0,0);")
        self.label_25 = QLabel(self.page_5)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(290, 175, 171, 21))
        self.label_25.setFont(font4)
        self.label_25.setStyleSheet(u"color: rgb(0,0,0);")
        self.label_26 = QLabel(self.page_5)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(540, 175, 171, 21))
        self.label_26.setFont(font4)
        self.label_26.setStyleSheet(u"color: rgb(0,0,0);")
        self.label_27 = QLabel(self.page_5)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(790, 175, 171, 21))
        self.label_27.setFont(font4)
        self.label_27.setStyleSheet(u"color: rgb(0,0,0);")
        self.label_28 = QLabel(self.page_5)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(260, 240, 201, 21))
        font5 = QFont()
        font5.setPointSize(15)
        font5.setBold(True)
        self.label_28.setFont(font5)
        self.label_28.setStyleSheet(u"color: rgb(0,0,0);")
        self.label_30 = QLabel(self.page_5)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(270, 90, 241, 21))
        font6 = QFont()
        font6.setPointSize(22)
        self.label_30.setFont(font6)
        self.label_30.setStyleSheet(u"color: rgb(0,0,0);")
        self.label_35 = QLabel(self.page_5)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 80, 31, 31))
        self.label_35.setStyleSheet(u"background-image: url(:/pics/images/home.png);")
        self.closeButton_3 = QPushButton(self.page_5)
        self.closeButton_3.setObjectName(u"closeButton_3")
        self.closeButton_3.setGeometry(QRect(980, 11, 31, 31))
        sizePolicy.setHeightForWidth(self.closeButton_3.sizePolicy().hasHeightForWidth())
        self.closeButton_3.setSizePolicy(sizePolicy)
        self.closeButton_3.setBaseSize(QSize(0, 0))
        self.closeButton_3.setStyleSheet(u"QPushButton#closeButton_3 {\n"
"    border: none;\n"
"    border-radius: 10px; /* set the initial border radius */\n"
"}\n"
"\n"
"QPushButton#closeButton_3:hover {\n"
"    border: 2px dashed grey; /* set the border to a solid color when hovering */\n"
"    border-radius: 50%; /* set the border radius to create a circle */\n"
"}\n"
"")
        self.closeButton_3.setIcon(icon)
        self.goDashboardButton = QPushButton(self.page_5)
        self.goDashboardButton.setObjectName(u"goDashboardButton")
        self.goDashboardButton.setGeometry(QRect(0, 70, 261, 61))
        self.goDashboardButton.setFont(font4)
        self.goDashboardButton.setStyleSheet(u"QPushButton#goDashboardButton {\n"
"    border: none;\n"
"    border-radius: 10px; /* set the initial border radius */\n"
"	color: rgb(0,0,0);\n"
"}\n"
"QPushButton#goDashboardButton:hover {\n"
"    background-color: rgb(81,74,200);\n"
"}\n"
"")
        self.goAccountButton = QPushButton(self.page_5)
        self.goAccountButton.setObjectName(u"goAccountButton")
        self.goAccountButton.setGeometry(QRect(0, 130, 261, 61))
        self.goAccountButton.setFont(font4)
        self.goAccountButton.setStyleSheet(u"QPushButton#goAccountButton {\n"
"    border: none;\n"
"    border-radius: 10px; /* set the initial border radius */\n"
"	color: rgb(0,0,0);\n"
"}\n"
"QPushButton#goAccountButton:hover {\n"
"    background-color: rgb(81,74,200);\n"
"}")
        self.goTransButton = QPushButton(self.page_5)
        self.goTransButton.setObjectName(u"goTransButton")
        self.goTransButton.setGeometry(QRect(0, 190, 261, 61))
        self.goTransButton.setFont(font4)
        self.goTransButton.setStyleSheet(u"QPushButton#goTransButton {\n"
"    border: none;\n"
"    border-radius: 10px; /* set the initial border radius */\n"
"	color: rgb(0,0,0);\n"
"}\n"
"QPushButton#goTransButton:hover {\n"
"    background-color: rgb(81,74,200);\n"
"}")
        self.goGoalButton = QPushButton(self.page_5)
        self.goGoalButton.setObjectName(u"goGoalButton")
        self.goGoalButton.setGeometry(QRect(0, 250, 261, 61))
        self.goGoalButton.setFont(font4)
        self.goGoalButton.setStyleSheet(u"QPushButton#goGoalButton {\n"
"    border: none;\n"
"    border-radius: 10px; /* set the initial border radius */\n"
"	color: rgb(0,0,0);\n"
"}\n"
"QPushButton#goGoalButton:hover {\n"
"    background-color: rgb(81,74,200);\n"
"}")
        self.label_36 = QLabel(self.page_5)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 140, 31, 31))
        self.label_36.setStyleSheet(u"")
        self.label_36.setPixmap(QPixmap(u":/pics/images/user.png"))
        self.label_36.setScaledContents(True)
        self.label_37 = QLabel(self.page_5)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 200, 31, 31))
        self.label_37.setStyleSheet(u"")
        self.label_37.setPixmap(QPixmap(u":/pics/images/trans.png"))
        self.label_37.setScaledContents(True)
        self.label_38 = QLabel(self.page_5)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 260, 31, 31))
        self.label_38.setStyleSheet(u"")
        self.label_38.setPixmap(QPixmap(u":/pics/images/goal.png"))
        self.label_38.setScaledContents(True)
        self.label_31 = QLabel(self.page_5)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(290, 300, 60, 16))
        font7 = QFont()
        font7.setPointSize(14)
        self.label_31.setFont(font7)
        self.label_31.setStyleSheet(u"color: rgb(148,148,148);")
        self.label_32 = QLabel(self.page_5)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(430, 300, 60, 16))
        self.label_32.setFont(font7)
        self.label_32.setStyleSheet(u"color: rgb(148,148,148);")
        self.label_33 = QLabel(self.page_5)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(820, 300, 81, 16))
        self.label_33.setFont(font7)
        self.label_33.setStyleSheet(u"color: rgb(148,148,148);")
        self.label_34 = QLabel(self.page_5)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(600, 300, 60, 16))
        self.label_34.setFont(font7)
        self.label_34.setStyleSheet(u"color: rgb(148,148,148);")
        self.line_2 = QFrame(self.page_5)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(260, 320, 751, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.page_5)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(260, 360, 751, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(self.page_5)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(260, 400, 751, 16))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_5 = QFrame(self.page_5)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(260, 440, 751, 16))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.line_6 = QFrame(self.page_5)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(260, 480, 751, 16))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.line_7 = QFrame(self.page_5)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(260, 520, 751, 16))
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.line_8 = QFrame(self.page_5)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(260, 560, 751, 16))
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.line_9 = QFrame(self.page_5)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(260, 600, 751, 16))
        self.line_9.setFrameShape(QFrame.HLine)
        self.line_9.setFrameShadow(QFrame.Sunken)
        self.line_10 = QFrame(self.page_5)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(260, 640, 751, 16))
        self.line_10.setFrameShape(QFrame.HLine)
        self.line_10.setFrameShadow(QFrame.Sunken)
        self.line_11 = QFrame(self.page_5)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(260, 680, 751, 16))
        self.line_11.setFrameShape(QFrame.HLine)
        self.line_11.setFrameShadow(QFrame.Sunken)
        self.line_12 = QFrame(self.page_5)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(260, 720, 751, 16))
        self.line_12.setFrameShape(QFrame.HLine)
        self.line_12.setFrameShadow(QFrame.Sunken)
        self.DateLabel1 = QLabel(self.page_5)
        self.DateLabel1.setObjectName(u"DateLabel1")
        self.DateLabel1.setGeometry(QRect(280, 340, 81, 16))
        self.DateLabel1.setStyleSheet(u"color: rgb(0,0,0);")
        self.DateLabel2 = QLabel(self.page_5)
        self.DateLabel2.setObjectName(u"DateLabel2")
        self.DateLabel2.setGeometry(QRect(280, 380, 81, 16))
        self.DateLabel2.setStyleSheet(u"color: rgb(0,0,0);")
        self.DateLabel3 = QLabel(self.page_5)
        self.DateLabel3.setObjectName(u"DateLabel3")
        self.DateLabel3.setGeometry(QRect(280, 420, 81, 16))
        self.DateLabel3.setStyleSheet(u"color: rgb(0,0,0);")
        self.DateLabel6 = QLabel(self.page_5)
        self.DateLabel6.setObjectName(u"DateLabel6")
        self.DateLabel6.setGeometry(QRect(280, 540, 81, 16))
        self.DateLabel6.setStyleSheet(u"color: rgb(0,0,0);")
        self.DateLabel4 = QLabel(self.page_5)
        self.DateLabel4.setObjectName(u"DateLabel4")
        self.DateLabel4.setGeometry(QRect(280, 460, 81, 16))
        self.DateLabel4.setStyleSheet(u"color: rgb(0,0,0);")
        self.DateLabel8 = QLabel(self.page_5)
        self.DateLabel8.setObjectName(u"DateLabel8")
        self.DateLabel8.setGeometry(QRect(280, 620, 81, 16))
        self.DateLabel8.setStyleSheet(u"color: rgb(0,0,0);")
        self.DateLabel7 = QLabel(self.page_5)
        self.DateLabel7.setObjectName(u"DateLabel7")
        self.DateLabel7.setGeometry(QRect(280, 580, 81, 16))
        self.DateLabel7.setStyleSheet(u"color: rgb(0,0,0);")
        self.DateLabel5 = QLabel(self.page_5)
        self.DateLabel5.setObjectName(u"DateLabel5")
        self.DateLabel5.setGeometry(QRect(280, 500, 81, 16))
        self.DateLabel5.setStyleSheet(u"color: rgb(0,0,0);")
        self.DateLabel10 = QLabel(self.page_5)
        self.DateLabel10.setObjectName(u"DateLabel10")
        self.DateLabel10.setGeometry(QRect(280, 700, 81, 16))
        self.DateLabel10.setStyleSheet(u"color: rgb(0,0,0);")
        self.DateLabel9 = QLabel(self.page_5)
        self.DateLabel9.setObjectName(u"DateLabel9")
        self.DateLabel9.setGeometry(QRect(280, 660, 81, 16))
        self.DateLabel9.setStyleSheet(u"color: rgb(0,0,0);")
        self.DateLabel11 = QLabel(self.page_5)
        self.DateLabel11.setObjectName(u"DateLabel11")
        self.DateLabel11.setGeometry(QRect(280, 740, 81, 16))
        self.DateLabel11.setStyleSheet(u"color: rgb(0,0,0);")
        self.AmountLabel9 = QLabel(self.page_5)
        self.AmountLabel9.setObjectName(u"AmountLabel9")
        self.AmountLabel9.setGeometry(QRect(420, 660, 91, 16))
        self.AmountLabel9.setStyleSheet(u"color: rgb(0,0,0);")
        self.AmountLabel2 = QLabel(self.page_5)
        self.AmountLabel2.setObjectName(u"AmountLabel2")
        self.AmountLabel2.setGeometry(QRect(420, 380, 91, 16))
        self.AmountLabel2.setStyleSheet(u"color: rgb(0,0,0);")
        self.AmountLabel10 = QLabel(self.page_5)
        self.AmountLabel10.setObjectName(u"AmountLabel10")
        self.AmountLabel10.setGeometry(QRect(420, 700, 101, 16))
        self.AmountLabel10.setStyleSheet(u"color: rgb(0,0,0);")
        self.AmountLabel11 = QLabel(self.page_5)
        self.AmountLabel11.setObjectName(u"AmountLabel11")
        self.AmountLabel11.setGeometry(QRect(420, 740, 101, 16))
        self.AmountLabel11.setStyleSheet(u"color: rgb(0,0,0);")
        self.AmountLabel7 = QLabel(self.page_5)
        self.AmountLabel7.setObjectName(u"AmountLabel7")
        self.AmountLabel7.setGeometry(QRect(420, 580, 91, 16))
        self.AmountLabel7.setStyleSheet(u"color: rgb(0,0,0);")
        self.AmountLabel8 = QLabel(self.page_5)
        self.AmountLabel8.setObjectName(u"AmountLabel8")
        self.AmountLabel8.setGeometry(QRect(420, 620, 91, 16))
        self.AmountLabel8.setStyleSheet(u"color: rgb(0,0,0);")
        self.AmountLabel1 = QLabel(self.page_5)
        self.AmountLabel1.setObjectName(u"AmountLabel1")
        self.AmountLabel1.setGeometry(QRect(420, 340, 91, 16))
        self.AmountLabel1.setStyleSheet(u"color: rgb(0,0,0);")
        self.AmountLabel5 = QLabel(self.page_5)
        self.AmountLabel5.setObjectName(u"AmountLabel5")
        self.AmountLabel5.setGeometry(QRect(420, 500, 91, 16))
        self.AmountLabel5.setStyleSheet(u"color: rgb(0,0,0);")
        self.AmountLabel3 = QLabel(self.page_5)
        self.AmountLabel3.setObjectName(u"AmountLabel3")
        self.AmountLabel3.setGeometry(QRect(420, 420, 91, 16))
        self.AmountLabel3.setStyleSheet(u"color: rgb(0,0,0);")
        self.AmountLabel4 = QLabel(self.page_5)
        self.AmountLabel4.setObjectName(u"AmountLabel4")
        self.AmountLabel4.setGeometry(QRect(420, 460, 91, 16))
        self.AmountLabel4.setStyleSheet(u"color: rgb(0,0,0);")
        self.AmountLabel6 = QLabel(self.page_5)
        self.AmountLabel6.setObjectName(u"AmountLabel6")
        self.AmountLabel6.setGeometry(QRect(420, 540, 91, 16))
        self.AmountLabel6.setStyleSheet(u"color: rgb(0,0,0);")
        self.CatLabel9 = QLabel(self.page_5)
        self.CatLabel9.setObjectName(u"CatLabel9")
        self.CatLabel9.setGeometry(QRect(600, 660, 81, 16))
        self.CatLabel9.setStyleSheet(u"color: rgb(0,0,0);")
        self.CatLabel2 = QLabel(self.page_5)
        self.CatLabel2.setObjectName(u"CatLabel2")
        self.CatLabel2.setGeometry(QRect(600, 380, 81, 16))
        self.CatLabel2.setStyleSheet(u"color: rgb(0,0,0);")
        self.CatLabel10 = QLabel(self.page_5)
        self.CatLabel10.setObjectName(u"CatLabel10")
        self.CatLabel10.setGeometry(QRect(600, 700, 81, 16))
        self.CatLabel10.setStyleSheet(u"color: rgb(0,0,0);")
        self.CatLabel11 = QLabel(self.page_5)
        self.CatLabel11.setObjectName(u"CatLabel11")
        self.CatLabel11.setGeometry(QRect(600, 740, 81, 16))
        self.CatLabel11.setStyleSheet(u"color: rgb(0,0,0);")
        self.CatLabel7 = QLabel(self.page_5)
        self.CatLabel7.setObjectName(u"CatLabel7")
        self.CatLabel7.setGeometry(QRect(600, 580, 81, 16))
        self.CatLabel7.setStyleSheet(u"color: rgb(0,0,0);")
        self.CatLabel8 = QLabel(self.page_5)
        self.CatLabel8.setObjectName(u"CatLabel8")
        self.CatLabel8.setGeometry(QRect(600, 620, 81, 16))
        self.CatLabel8.setStyleSheet(u"color: rgb(0,0,0);")
        self.CatLabel1 = QLabel(self.page_5)
        self.CatLabel1.setObjectName(u"CatLabel1")
        self.CatLabel1.setGeometry(QRect(600, 340, 81, 16))
        self.CatLabel1.setStyleSheet(u"color: rgb(0,0,0);")
        self.CatLabel5 = QLabel(self.page_5)
        self.CatLabel5.setObjectName(u"CatLabel5")
        self.CatLabel5.setGeometry(QRect(600, 500, 81, 16))
        self.CatLabel5.setStyleSheet(u"color: rgb(0,0,0);")
        self.CatLabel3 = QLabel(self.page_5)
        self.CatLabel3.setObjectName(u"CatLabel3")
        self.CatLabel3.setGeometry(QRect(600, 420, 81, 16))
        self.CatLabel3.setStyleSheet(u"color: rgb(0,0,0);")
        self.CatLabel4 = QLabel(self.page_5)
        self.CatLabel4.setObjectName(u"CatLabel4")
        self.CatLabel4.setGeometry(QRect(600, 460, 81, 16))
        self.CatLabel4.setStyleSheet(u"color: rgb(0,0,0);")
        self.CatLabel6 = QLabel(self.page_5)
        self.CatLabel6.setObjectName(u"CatLabel6")
        self.CatLabel6.setGeometry(QRect(600, 540, 81, 16))
        self.CatLabel6.setStyleSheet(u"color: rgb(0,0,0);")
        self.DesLabel9 = QLabel(self.page_5)
        self.DesLabel9.setObjectName(u"DesLabel9")
        self.DesLabel9.setGeometry(QRect(830, 660, 81, 16))
        self.DesLabel9.setStyleSheet(u"color: rgb(0,0,0);")
        self.DesLabel2 = QLabel(self.page_5)
        self.DesLabel2.setObjectName(u"DesLabel2")
        self.DesLabel2.setGeometry(QRect(830, 380, 81, 16))
        self.DesLabel2.setStyleSheet(u"color: rgb(0,0,0);")
        self.DesLabel10 = QLabel(self.page_5)
        self.DesLabel10.setObjectName(u"DesLabel10")
        self.DesLabel10.setGeometry(QRect(830, 700, 81, 16))
        self.DesLabel10.setStyleSheet(u"color: rgb(0,0,0);")
        self.DateLabel11_2 = QLabel(self.page_5)
        self.DateLabel11_2.setObjectName(u"DateLabel11_2")
        self.DateLabel11_2.setGeometry(QRect(830, 740, 81, 16))
        self.DateLabel11_2.setStyleSheet(u"color: rgb(0,0,0);")
        self.DesLabel7 = QLabel(self.page_5)
        self.DesLabel7.setObjectName(u"DesLabel7")
        self.DesLabel7.setGeometry(QRect(830, 580, 81, 16))
        self.DesLabel7.setStyleSheet(u"color: rgb(0,0,0);")
        self.DesLabel8 = QLabel(self.page_5)
        self.DesLabel8.setObjectName(u"DesLabel8")
        self.DesLabel8.setGeometry(QRect(830, 620, 81, 16))
        self.DesLabel8.setStyleSheet(u"color: rgb(0,0,0);")
        self.DesLabel1 = QLabel(self.page_5)
        self.DesLabel1.setObjectName(u"DesLabel1")
        self.DesLabel1.setGeometry(QRect(830, 340, 81, 16))
        self.DesLabel1.setStyleSheet(u"color: rgb(0,0,0);")
        self.DesLabel5 = QLabel(self.page_5)
        self.DesLabel5.setObjectName(u"DesLabel5")
        self.DesLabel5.setGeometry(QRect(830, 500, 81, 16))
        self.DesLabel5.setStyleSheet(u"color: rgb(0,0,0);")
        self.DesLabel3 = QLabel(self.page_5)
        self.DesLabel3.setObjectName(u"DesLabel3")
        self.DesLabel3.setGeometry(QRect(830, 420, 81, 16))
        self.DesLabel3.setStyleSheet(u"color: rgb(0,0,0);")
        self.DesLabel4 = QLabel(self.page_5)
        self.DesLabel4.setObjectName(u"DesLabel4")
        self.DesLabel4.setGeometry(QRect(830, 460, 81, 16))
        self.DesLabel4.setStyleSheet(u"color: rgb(0,0,0);")
        self.DesLabel6 = QLabel(self.page_5)
        self.DesLabel6.setObjectName(u"DesLabel6")
        self.DesLabel6.setGeometry(QRect(830, 540, 81, 16))
        self.DesLabel6.setStyleSheet(u"color: rgb(0,0,0);")
        self.stackedWidget.addWidget(self.page_5)
        self.label_12.raise_()
        self.label_11.raise_()
        self.label_3.raise_()
        self.label_8.raise_()
        self.label_16.raise_()
        self.label_13.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_30.raise_()
        self.closeButton_3.raise_()
        self.tabsButton.raise_()
        self.goDashboardButton.raise_()
        self.label_35.raise_()
        self.goAccountButton.raise_()
        self.goTransButton.raise_()
        self.goGoalButton.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.line_9.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        self.line_12.raise_()
        self.DateLabel1.raise_()
        self.DateLabel2.raise_()
        self.DateLabel3.raise_()
        self.DateLabel6.raise_()
        self.DateLabel4.raise_()
        self.DateLabel8.raise_()
        self.DateLabel7.raise_()
        self.DateLabel5.raise_()
        self.DateLabel10.raise_()
        self.DateLabel9.raise_()
        self.DateLabel11.raise_()
        self.AmountLabel9.raise_()
        self.AmountLabel2.raise_()
        self.AmountLabel10.raise_()
        self.AmountLabel11.raise_()
        self.AmountLabel7.raise_()
        self.AmountLabel8.raise_()
        self.AmountLabel1.raise_()
        self.AmountLabel5.raise_()
        self.AmountLabel3.raise_()
        self.AmountLabel4.raise_()
        self.AmountLabel6.raise_()
        self.CatLabel9.raise_()
        self.CatLabel2.raise_()
        self.CatLabel10.raise_()
        self.CatLabel11.raise_()
        self.CatLabel7.raise_()
        self.CatLabel8.raise_()
        self.CatLabel1.raise_()
        self.CatLabel5.raise_()
        self.CatLabel3.raise_()
        self.CatLabel4.raise_()
        self.CatLabel6.raise_()
        self.DesLabel9.raise_()
        self.DesLabel2.raise_()
        self.DesLabel10.raise_()
        self.DateLabel11_2.raise_()
        self.DesLabel7.raise_()
        self.DesLabel8.raise_()
        self.DesLabel1.raise_()
        self.DesLabel5.raise_()
        self.DesLabel3.raise_()
        self.DesLabel4.raise_()
        self.DesLabel6.raise_()

        self.retranslateUi(Form)
        self.closeButton.clicked.connect(Form.close)
        self.closeButton_2.clicked.connect(Form.close)
        self.closeButton_3.clicked.connect(Form.close)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText("")
        self.label_2.setText("")
        self.Signin_Label.setText(QCoreApplication.translate("Form", u"Sign In", None))
        self.lineEditUserLogin.setPlaceholderText(QCoreApplication.translate("Form", u"Username", None))
        self.loginButton.setText(QCoreApplication.translate("Form", u"S i g n  I n", None))
        self.GoRegisterButton.setText(QCoreApplication.translate("Form", u"G o  R e g i s t er", None))
        self.label_4.setText("")
        self.label_5.setText(QCoreApplication.translate("Form", u"Money Mate", None))
        self.lineEditPassLogin.setPlaceholderText(QCoreApplication.translate("Form", u"Password", None))
        self.closeButton.setText("")
        self.label_6.setText("")
        self.label_7.setText("")
        self.Reigstration_Label.setText(QCoreApplication.translate("Form", u"Registration", None))
        self.lineEditUserRegister.setPlaceholderText(QCoreApplication.translate("Form", u"Username", None))
        self.RegisterButton.setText(QCoreApplication.translate("Form", u"R e g i s t er", None))
        self.label_9.setText("")
        self.label_10.setText(QCoreApplication.translate("Form", u"Money Mate", None))
        self.lineEditUserPassword.setPlaceholderText(QCoreApplication.translate("Form", u"Password", None))
        self.closeButton_2.setText("")
        self.lineEditUserPassword_2.setPlaceholderText(QCoreApplication.translate("Form", u"Confirm Password", None))
        self.goSigninButton.setText(QCoreApplication.translate("Form", u"B a c k  to  S i g n I n", None))
        self.label_3.setText("")
        self.label_8.setText(QCoreApplication.translate("Form", u"Money Mate", None))
        self.tabsButton.setText("")
        self.label_11.setText("")
        self.label_12.setText("")
        self.label_13.setText("")
        self.label_14.setText("")
        self.label_15.setText("")
        self.label_16.setText("")
        self.label_17.setText("")
        self.label_18.setText("")
        self.label_19.setText(QCoreApplication.translate("Form", u"Current Balance", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"Available Balance", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"Spent This Week", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"\u0e3f", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"\u0e3f", None))
        self.label_24.setText(QCoreApplication.translate("Form", u"\u0e3f", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_26.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_27.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_28.setText(QCoreApplication.translate("Form", u"Account Transaction:", None))
        self.label_30.setText(QCoreApplication.translate("Form", u"\u2190 User Account", None))
        self.label_35.setText("")
        self.closeButton_3.setText("")
        self.goDashboardButton.setText(QCoreApplication.translate("Form", u"Dashboard", None))
        self.goAccountButton.setText(QCoreApplication.translate("Form", u"Account", None))
        self.goTransButton.setText(QCoreApplication.translate("Form", u"Transactions", None))
        self.goGoalButton.setText(QCoreApplication.translate("Form", u"Goal", None))
        self.label_36.setText("")
        self.label_37.setText("")
        self.label_38.setText("")
        self.label_31.setText(QCoreApplication.translate("Form", u"Date", None))
        self.label_32.setText(QCoreApplication.translate("Form", u"Amount", None))
        self.label_33.setText(QCoreApplication.translate("Form", u"Description", None))
        self.label_34.setText(QCoreApplication.translate("Form", u"Category", None))
        self.DateLabel1.setText(QCoreApplication.translate("Form", u"DateLabel1", None))
        self.DateLabel2.setText(QCoreApplication.translate("Form", u"DateLabel2", None))
        self.DateLabel3.setText(QCoreApplication.translate("Form", u"DateLabel3", None))
        self.DateLabel6.setText(QCoreApplication.translate("Form", u"DateLabel6", None))
        self.DateLabel4.setText(QCoreApplication.translate("Form", u"DateLabel4", None))
        self.DateLabel8.setText(QCoreApplication.translate("Form", u"DateLabel8", None))
        self.DateLabel7.setText(QCoreApplication.translate("Form", u"DateLabel7", None))
        self.DateLabel5.setText(QCoreApplication.translate("Form", u"DateLabel5", None))
        self.DateLabel10.setText(QCoreApplication.translate("Form", u"DateLabel10", None))
        self.DateLabel9.setText(QCoreApplication.translate("Form", u"DateLabel9", None))
        self.DateLabel11.setText(QCoreApplication.translate("Form", u"DateLabel11", None))
        self.AmountLabel9.setText(QCoreApplication.translate("Form", u"AmountLabel9", None))
        self.AmountLabel2.setText(QCoreApplication.translate("Form", u"AmountLabel2", None))
        self.AmountLabel10.setText(QCoreApplication.translate("Form", u"AmountLabel10", None))
        self.AmountLabel11.setText(QCoreApplication.translate("Form", u"AmountLabel11", None))
        self.AmountLabel7.setText(QCoreApplication.translate("Form", u"AmountLabel7", None))
        self.AmountLabel8.setText(QCoreApplication.translate("Form", u"AmountLabel8", None))
        self.AmountLabel1.setText(QCoreApplication.translate("Form", u"AmountLabel1", None))
        self.AmountLabel5.setText(QCoreApplication.translate("Form", u"AmountLabel5", None))
        self.AmountLabel3.setText(QCoreApplication.translate("Form", u"AmountLabel3", None))
        self.AmountLabel4.setText(QCoreApplication.translate("Form", u"AmountLabel4", None))
        self.AmountLabel6.setText(QCoreApplication.translate("Form", u"AmountLabel6", None))
        self.CatLabel9.setText(QCoreApplication.translate("Form", u"CatLabel9", None))
        self.CatLabel2.setText(QCoreApplication.translate("Form", u"CatLabel2", None))
        self.CatLabel10.setText(QCoreApplication.translate("Form", u"CatLabel10", None))
        self.CatLabel11.setText(QCoreApplication.translate("Form", u"CatLabel11", None))
        self.CatLabel7.setText(QCoreApplication.translate("Form", u"CatLabel7", None))
        self.CatLabel8.setText(QCoreApplication.translate("Form", u"CatLabel8", None))
        self.CatLabel1.setText(QCoreApplication.translate("Form", u"CatLabel1", None))
        self.CatLabel5.setText(QCoreApplication.translate("Form", u"CatLabel5", None))
        self.CatLabel3.setText(QCoreApplication.translate("Form", u"CatLabel3", None))
        self.CatLabel4.setText(QCoreApplication.translate("Form", u"CatLabel4", None))
        self.CatLabel6.setText(QCoreApplication.translate("Form", u"CatLabel6", None))
        self.DesLabel9.setText(QCoreApplication.translate("Form", u"DesLabel9", None))
        self.DesLabel2.setText(QCoreApplication.translate("Form", u"DesLabel2", None))
        self.DesLabel10.setText(QCoreApplication.translate("Form", u"DesLabel10", None))
        self.DateLabel11_2.setText(QCoreApplication.translate("Form", u"DesLabel11", None))
        self.DesLabel7.setText(QCoreApplication.translate("Form", u"DesLabel7", None))
        self.DesLabel8.setText(QCoreApplication.translate("Form", u"DesLabel8", None))
        self.DesLabel1.setText(QCoreApplication.translate("Form", u"DesLabel1", None))
        self.DesLabel5.setText(QCoreApplication.translate("Form", u"DesLabel5", None))
        self.DesLabel3.setText(QCoreApplication.translate("Form", u"DesLabel3", None))
        self.DesLabel4.setText(QCoreApplication.translate("Form", u"DesLabel4", None))
        self.DesLabel6.setText(QCoreApplication.translate("Form", u"DesLabel6", None))
    # retranslateUi

